### ISSUE TITLE
参数错误

### ISSUE THREAD

**Issue by liaosunny123** [Under-estimate/Mirai-wiki#2]
wiki插件参数错误
每个命令都是的，按照readme输入的

另外如果有兴趣能加入emg吗，emg是一个启动器，里面有插件中心可以方便让你的插件给更多用户直接下载安装，可以参见epicmomiraig项目

**Comment by Under-estimate** [comment]
请问是在后台命令行输入的命令还是在QQ群中发送的命令呢?
目前只支持在QQ群中发送命令，因为每次提问/回答需要记录执行该操作的用户。

> 之后会考虑加入EpicMoMiraiG。

**Comment by liaosunny123** [comment]
命令台，我看看qq群

EMG昨天拉取了您插件，目前有6个用户下载了您的插件，您可以访问www.github.com/liaosunny123/epicmomiraig看查项目，mirai论坛也有，也有qq群，你可以自由托管您的插件文件(可见mirai论坛帖子)

谢谢，我康康咋用

**Comment by liaosunny123** [comment]
还是没有反应，在q群

**Comment by liaosunny123** [comment]
加/和不加都试了，控制台参数不足，q群插件不会反应

**Comment by Under-estimate** [comment]
请确认同时添加了[chat-command](https://github.com/project-mirai/chat-command)插件，mirai-console需要此插件来支持解析QQ群中发送的命令。以及为执行命令的用户[授予相关权限](https://github.com/mamoe/mirai-console/blob/master/docs/Permissions.md)。

改用了mirai最新的命令/权限系统之后插件使用文档没有更新，之后我会在插件文档中增添相关教程。
> - [x] 补充插件使用文档。

**Comment by liaosunny123** [comment]
还是不行诶

**Comment by liaosunny123** [comment]
哦哦，看到了，我设置下权限

**Comment by liaosunny123** [comment]
还是不行

**Comment by Under-estimate** [comment]
> 还是不行

是QQ群消息没有反应吗?  
请尝试发送带`/`前缀的命令，如`/wiki about`。  
  
如果问题仍未解决，您可以将QQ号发送至[我的邮箱](mailto:1260717118@qq.com)进一步讨论。

**Comment by Under-estimate** [comment]
用户反映该问题已解决
