### ISSUE TITLE
/wiki question的使用方法

### ISSUE THREAD

**Issue by mojizooo** [Under-estimate/Mirai-wiki#3]
如图
![1LO3 P~`IFK)6YXADB_(}_T](https://user-images.githubusercontent.com/82160301/114869376-79d85300-9e29-11eb-990e-d37c7b451a4c.png)

**Comment by Under-estimate** [comment]
`/wiki question`命令只是开始创建问题，输入此命令之后可以通过`/wiki text`和`/wiki image`命令为问题添加文本和图片，最后输入`/wiki submit`以提交问题，或`/wiki abort`放弃创建问题。
