### ISSUE TITLE
/wiki all terminal中报错 功能正常

### ISSUE THREAD

**Issue by Alkaidcc** [Under-estimate/Mirai-wiki#4]
当我没有创建任何问题，输入`/wiki all`时，命令行显示如下：

![image](https://user-images.githubusercontent.com/54631354/131823750-722a10e0-19e4-4a46-8935-dc0ed149eb90.png)

Bot回复  `本群还没有人提过问题`
- 也许是空问题引起的空指针错误（

**Comment by Under-estimate** [comment]
此问题已修复，[在此获取最新的插件文件](https://github.com/Under-estimate/Mirai-wiki/releases/)
